---

- name: Ensure Apache Installed
  apt : name=apache2 state=present
  when: ansible_os_family == "Debian"
- name: Start Apache
  service: name=apache2 enabled=yes state=started


- name: Copy Site Files
  template: src=index.html.j2 dest=/var/www/html/ansible/index.html
 
